### ISSUE TITLE
fourthcorner.rlq() causes R session abort due to fatal error 

### ISSUE THREAD

**Issue by maurinka** [adeverse/ade4#43]
@sdray

Running the fourthcorner.rlq() function to directly test links between RLQ axes and traits / environmental variables causes R session abort (fatal error).

R studio, R and the package are up-to-date:

RStudio 2024.09.1+394 "Cranberry Hibiscus" Release (a1fe401fc08c232d470278d1bc362d05d79753d9, 2024-11-03) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.09.1+394 Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36, Quarto 1.4.553 (C:/Program Files/Quarto/bin/quarto.exe)

R version 4.4.1 (2024-06-14 ucrt)

> packageVersion('ade4')
[1] ‘1.7.22’

![CRASH](https://github.com/user-attachments/assets/90fc28fa-61b4-4dab-8686-953163ec309c)

**Comment by sdray** [comment]
Hi, it is hard to help to identify the problem without a reproducible example. Could you send (possibly by email) R code and data so that I can reproduce the problem. 

Cheers

**Comment by maurinka** [comment]
hi @sdray 

thank you for the swift reply! just sent an email with code and data used to email address that I found online (@univ-lyon1.fr).

cheers!

**Comment by sdray** [comment]
I am sorry but I did not receive your email

**Comment by maurinka** [comment]
I sent you the email again. I receive a message that there is a spam filter. @sdray

**Comment by sdray** [comment]
yes, I received the files and identified the problem. In your traits data, the first variable is a factor that has unused levels (probably due to subselection of species):

```
> summary(dat$traits)
            hunting_guild  avg_body_len             Stratum                                    Ecology  
 ActiveHunters     :17    Min.   : 1.450   ground/litter:19   agriculture/forest/wetlands/grassland: 7  
 AmbushPredator    : 3    1st Qu.: 2.400   ground/soil  :11   agriculture/forest/wetlands/open     :17  
 JumpingSpiders    : 0    Median : 3.550   litter/tree  : 4   forest/grassland                     : 4  
 WebBuilding_Orb   : 0    Mean   : 4.296                      grassland/ruderal/open               : 6  
 WebBuilding_Sheet :13    3rd Qu.: 5.507                                                                
 WebBuilding_Tangle: 1    Max.   :10.375                                                                
 Dispersal
 high:15  
 low : 7  
 mid :12
```  
          
If you remove these unused levels (for instance by forcing the removing with the `factor` function), the problem is solved:          
          
```
> dat$traits[,1] <- factor(dat$traits[,1])
> summary(dat$traits)
            hunting_guild  avg_body_len             Stratum                                    Ecology  
 ActiveHunters     :17    Min.   : 1.450   ground/litter:19   agriculture/forest/wetlands/grassland: 7  
 AmbushPredator    : 3    1st Qu.: 2.400   ground/soil  :11   agriculture/forest/wetlands/open     :17  
 WebBuilding_Sheet :13    Median : 3.550   litter/tree  : 4   forest/grassland                     : 4  
 WebBuilding_Tangle: 1    Mean   : 4.296                      grassland/ruderal/open               : 6  
                          3rd Qu.: 5.507                                                                
                          Max.   :10.375                                                                
 Dispersal
 high:15  
 low : 7  
 mid :12  

```
and the analysis works:

```
> fourthcorner.rlq(rlq.env,type="Q.axes")
Fourth-corner Statistics
------------------------
Permutation method  Comb. 2 and 4  ( 999  permutations)

Adjustment method for multiple comparisons:   holm 
call:  fourthcorner.rlq(xtest = rlq.env, typetest = "Q.axes") 

---

                                                  Test   Stat          Obs     Std.Obs     Alter Pvalue
1                          AxcR1 / hunti.ActiveHunters Homog. 0.5044940330 -1.66790847      less  0.055
2                          AxcR2 / hunti.ActiveHunters Homog. 0.5225419012 -0.99805261      less  0.172
3                         AxcR1 / hunti.AmbushPredator Homog. 0.0104348889 -0.24115721      less  0.419
```

Have a nice day.

**Comment by maurinka** [comment]
thank you!
